// src/lib/Settings.svelte
<script lang="ts">
  import Switch from "./ds/Switch.svelte";
  import Select from "./ds/Select.svelte";
  import Radio from "./ds/Radio.svelte";
  import Button from "./ds/Button.svelte";
  import { EMAIL_ACTIONS, initials, type Account } from "./data";

  let {
    accounts,
    hoverActions,
    onHoverActionsChange,
    pinListEnabled,
    onPinListChange,
  }: {
    accounts: Account[];
    hoverActions: string[];
    onHoverActionsChange: (next: string[]) => void;
    pinListEnabled: boolean;
    onPinListChange: (v: boolean) => void;
  } = $props();

  let signature = $state(true);
  let signatureText = $state("Peter\nHey Pigeon");
  let dragKey: string | null = $state(null);
  let readReceipts = $state(false);
  let desktopNotif = $state(true);
  let notifSound = $state(true);
  let notifPreview = $state("sender-subject");
  let density = $state("comfortable");
  let theme = $state("system");
  let swipeRight = $state("done");
  let autoAdvance = $state("newer");
  let blockTracking = $state(true);

  function reorderOrAdd(targetIndex: number) {
    if (!dragKey) return;
    let next = hoverActions.filter((k) => k !== dragKey);
    const insertAt = Math.min(targetIndex, next.length);
    next.splice(insertAt, 0, dragKey);
    if (next.length > 3) next = next.slice(0, 3);
    onHoverActionsChange(next);
    dragKey = null;
  }
</script>

{#snippet settingRow(title: string, description: string)}
  <div class="setting-row">
    <div class="setting-text">
      <div class="setting-title">{title}</div>
      {#if description}
        <div class="setting-desc">{description}</div>
      {/if}
    </div>
  </div>
{/snippet}

<div class="settings">
  <section>
    <div class="group-head">
      <h2>Accounts</h2>
      <p>Connected mailboxes shown in the sidebar.</p>
    </div>
    <div class="group-body">
      {#each accounts as a (a.id)}
        <div class="account-row">
          <span class="account-avatar" style:background="var(--tag-{a.tag}-bg)" style:color="var(--tag-{a.tag}-fg)"
            >{initials(a.label)}</span
          >
          <div class="account-text">
            <div class="setting-title">{a.label}</div>
            <div class="account-email">{a.email}</div>
          </div>
          <Button variant="ghost" size="sm">Remove</Button>
        </div>
      {/each}
      <div class="add-account">
        <Button variant="secondary" size="sm">Add account</Button>
      </div>
    </div>
  </section>

  <section>
    <div class="group-head"><h2>Notifications</h2></div>
    <div class="group-body">
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Desktop notifications</div>
          <div class="setting-desc">Show a system notification for new mail while Hey Pigeon is open.</div>
        </div>
        <div class="setting-control"><Switch bind:checked={desktopNotif} /></div>
      </div>
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Notification sound</div>
          <div class="setting-desc">Play a sound when new mail arrives.</div>
        </div>
        <div class="setting-control"><Switch bind:checked={notifSound} /></div>
      </div>
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Preview content</div>
          <div class="setting-desc">What to show in a new mail notification.</div>
        </div>
        <div class="setting-control">
          <Select
            bind:value={notifPreview}
            options={[
              { value: "sender-subject", label: "Sender & subject" },
              { value: "sender-only", label: "Sender only" },
              { value: "none", label: "Nothing" },
            ]}
          />
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="group-head"><h2>Appearance</h2></div>
    <div class="group-body">
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Theme</div>
          <div class="setting-desc">Match your system, or set Hey Pigeon independently.</div>
        </div>
        <div class="setting-control theme-radios">
          {#each [["system", "System"], ["light", "Light"], ["dark", "Dark"]] as [v, l] (v)}
            <Radio name="theme" label={l} checked={theme === v} onchange={() => (theme = v)} />
          {/each}
        </div>
      </div>
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">List density</div>
          <div class="setting-desc">How much space each message row takes up.</div>
        </div>
        <div class="setting-control">
          <Select
            bind:value={density}
            options={[
              { value: "comfortable", label: "Comfortable" },
              { value: "compact", label: "Compact" },
            ]}
          />
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="group-head">
      <h2>Inbox</h2>
      <p>Control how messages are grouped and which actions appear on hover.</p>
    </div>
    <div class="group-body">
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Pinned list</div>
          <div class="setting-desc">Group pinned messages at the top of your inbox, above the rest.</div>
        </div>
        <div class="setting-control">
          <Switch checked={pinListEnabled} onchange={(v) => onPinListChange(v)} />
        </div>
      </div>
      {@render settingRow("Hover actions", "Drag up to 3 actions into the box to show them when you hover a message.")}
      <div class="hover-actions">
        <div>
          <div class="drag-label">Selected (drag to reorder)</div>
          <div
            class="drop-zone"
            role="list"
            ondragover={(e) => e.preventDefault()}
            ondrop={(e) => {
              e.preventDefault();
              reorderOrAdd(hoverActions.length);
            }}
          >
            {#each hoverActions as k, i (k)}
              {@const a = EMAIL_ACTIONS.find((x) => x.key === k)}
              {#if a}
                <span
                  class="action-chip selected"
                  role="listitem"
                  draggable="true"
                  ondragstart={() => (dragKey = k)}
                  ondragend={() => (dragKey = null)}
                  ondragover={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                  }}
                  ondrop={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    reorderOrAdd(i);
                  }}
                >
                  {a.label}
                  <button class="chip-x" aria-label="Remove {a.label}" onclick={() => onHoverActionsChange(hoverActions.filter((x) => x !== k))}>
                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none">
                      <path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" />
                    </svg>
                  </button>
                </span>
              {/if}
            {/each}
            {#if hoverActions.length === 0}
              <span class="drop-hint">Drop actions here</span>
            {/if}
          </div>
        </div>
        <div>
          <div class="drag-label">Available</div>
          <div
            class="available-zone"
            role="list"
            ondragover={(e) => e.preventDefault()}
            ondrop={(e) => {
              e.preventDefault();
              if (dragKey) onHoverActionsChange(hoverActions.filter((k) => k !== dragKey));
              dragKey = null;
            }}
          >
            {#each EMAIL_ACTIONS.filter((a) => !hoverActions.includes(a.key)) as a (a.key)}
              <span
                class="action-chip"
                role="listitem"
                draggable="true"
                ondragstart={() => (dragKey = a.key)}
                ondragend={() => (dragKey = null)}
              >
                {a.label}
              </span>
            {/each}
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="group-head"><h2>Reading &amp; replying</h2></div>
    <div class="group-body">
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Include signature</div>
          <div class="setting-desc">Add your signature to new messages automatically.</div>
        </div>
        <div class="setting-control"><Switch bind:checked={signature} /></div>
      </div>
      {#if signature}
        <div class="signature-wrap">
          <textarea bind:value={signatureText} rows="4"></textarea>
        </div>
      {/if}
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Send read receipts</div>
          <div class="setting-desc">Let senders know when you've opened their message.</div>
        </div>
        <div class="setting-control"><Switch bind:checked={readReceipts} /></div>
      </div>
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Swipe right on a message</div>
          <div class="setting-desc">Choose what a right swipe does in the inbox list.</div>
        </div>
        <div class="setting-control">
          <Select
            bind:value={swipeRight}
            options={[
              { value: "done", label: "Mark done" },
              { value: "delete", label: "Delete" },
              { value: "snooze", label: "Snooze" },
            ]}
          />
        </div>
      </div>
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">After archiving or deleting</div>
          <div class="setting-desc">Which message to open next.</div>
        </div>
        <div class="setting-control">
          <Select
            bind:value={autoAdvance}
            options={[
              { value: "newer", label: "Newer message" },
              { value: "older", label: "Older message" },
              { value: "list", label: "Back to list" },
            ]}
          />
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="group-head"><h2>Privacy</h2></div>
    <div class="group-body">
      <div class="setting-row">
        <div class="setting-text">
          <div class="setting-title">Block external images by default</div>
          <div class="setting-desc">
            Stop remote images from loading until you choose to show them, to limit sender tracking.
          </div>
        </div>
        <div class="setting-control"><Switch bind:checked={blockTracking} /></div>
      </div>
    </div>
  </section>
</div>

<style>
  .settings {
    width: 100%;
    padding-bottom: 60px;
  }
  section {
    margin-bottom: 40px;
  }
  .group-head {
    margin-bottom: 4px;
  }
  .group-head h2 {
    margin: 0;
    font-family: var(--font-mono);
    font-weight: 600;
    font-size: 12px;
    color: var(--accent-highlight);
  }
  .group-head p {
    margin: 4px 0 0;
    font-family: var(--font-body);
    font-size: 13.5px;
    color: var(--text-tertiary);
  }
  .group-body {
    margin-top: 12px;
  }
  .setting-row {
    display: flex;
    align-items: center;
    gap: 24px;
    padding: 16px 0;
    border-bottom: 1px solid var(--navy-50);
  }
  .setting-text {
    flex: 1;
    min-width: 0;
  }
  .setting-title {
    font-family: var(--font-body);
    font-size: 14.5px;
    font-weight: 600;
    color: var(--text-primary);
  }
  .setting-desc {
    font-family: var(--font-body);
    font-size: 13px;
    color: var(--text-tertiary);
    margin-top: 3px;
    line-height: 1.5;
  }
  .setting-control {
    flex-shrink: 0;
  }
  .theme-radios {
    display: flex;
    gap: 18px;
  }
  .account-row {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 12px 0;
    border-bottom: 1px solid var(--navy-50);
  }
  .account-avatar {
    width: 32px;
    height: 32px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: var(--font-body);
    font-size: 13px;
    font-weight: 700;
    flex-shrink: 0;
  }
  .account-text {
    flex: 1;
    min-width: 0;
  }
  .account-email {
    font-family: var(--font-body);
    font-size: 13px;
    color: var(--text-tertiary);
  }
  .add-account {
    padding-top: 14px;
  }
  .hover-actions {
    display: flex;
    flex-direction: column;
    gap: 14px;
    padding: 0 0 16px;
  }
  .drag-label {
    font-family: var(--font-body);
    font-size: 12px;
    color: var(--text-tertiary);
    margin-bottom: 6px;
  }
  .drop-zone {
    display: flex;
    gap: 8px;
    min-height: 40px;
    align-items: center;
    padding: 8px;
    border: 1px dashed var(--border-default);
    border-radius: var(--radius-md);
  }
  .available-zone {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    min-height: 34px;
    padding: 8px;
  }
  .action-chip {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 12px;
    background: var(--surface-card);
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-pill);
    font-family: var(--font-body);
    font-size: 13px;
    color: var(--text-secondary);
    cursor: grab;
  }
  .action-chip.selected {
    padding: 6px 6px 6px 12px;
    background: var(--surface-sunken);
    border: none;
    font-weight: 600;
    color: var(--text-primary);
  }
  .chip-x {
    border: none;
    background: none;
    cursor: pointer;
    color: var(--text-tertiary);
    display: flex;
    padding: 4px;
  }
  .drop-hint {
    font-family: var(--font-body);
    font-size: 13px;
    color: var(--text-tertiary);
  }
  .signature-wrap {
    padding: 0 0 16px;
  }
  .signature-wrap textarea {
    width: 100%;
    box-sizing: border-box;
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-md);
    padding: 12px;
    resize: vertical;
    font-family: var(--font-body);
    font-size: 13.5px;
    color: var(--text-primary);
    outline: none;
    background: none;
  }
</style>

// prototype/Settings.jsx
function SettingRow({ title, description, control }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 24, padding: '16px 0', borderBottom: '1px solid var(--navy-50)' }}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontFamily: 'var(--font-body)', fontSize: 14.5, fontWeight: 600, color: 'var(--text-primary)' }}>{title}</div>
        {description && <div style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--text-tertiary)', marginTop: 3, lineHeight: 1.5 }}>{description}</div>}
      </div>
      <div style={{ flexShrink: 0 }}>{control}</div>
    </div>
  );
}

function SettingsGroup({ title, description, children }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <div style={{ marginBottom: 4 }}>
        <h2 style={{ margin: 0, fontFamily: 'var(--font-mono)', fontWeight: 600, fontSize: 12, color: 'var(--accent-highlight)' }}>{title}</h2>
        {description && <p style={{ margin: '4px 0 0', fontFamily: 'var(--font-body)', fontSize: 13.5, color: 'var(--text-tertiary)' }}>{description}</p>}
      </div>
      <div style={{ marginTop: 12 }}>{children}</div>
    </section>
  );
}

function Settings({ accounts, hoverActions, onHoverActionsChange, pinListEnabled, onPinListChange }) {
  const { Switch, Select, Radio, Avatar, Button } = window.VibeMailDesignSystem_b5a4d1;
  const [signature, setSignature] = React.useState('true');
  const [signatureText, setSignatureText] = React.useState('Peter\nHey Pigeon');
  const [dragKey, setDragKey] = React.useState(null);
  const [readReceipts, setReadReceipts] = React.useState(false);
  const [desktopNotif, setDesktopNotif] = React.useState(true);
  const [notifSound, setNotifSound] = React.useState(true);
  const [notifPreview, setNotifPreview] = React.useState('sender-subject');
  const [density, setDensity] = React.useState('comfortable');
  const [theme, setTheme] = React.useState('system');
  const [swipeRight, setSwipeRight] = React.useState('done');
  const [autoAdvance, setAutoAdvance] = React.useState('newer');
  const [blockTracking, setBlockTracking] = React.useState(true);
  const initials = (s) => s.split(/[@.\s]/).filter(Boolean).slice(0, 2).map((w) => w[0].toUpperCase()).join('');
  const reorderOrAdd = (targetIndex) => {
    if (!dragKey) return;
    let next = hoverActions.filter((k) => k !== dragKey);
    const insertAt = Math.min(targetIndex, next.length);
    next.splice(insertAt, 0, dragKey);
    if (next.length > 3) next = next.slice(0, 3);
    onHoverActionsChange(next);
    setDragKey(null);
  };

  return (
    <div style={{ width: '100%', paddingBottom: 60 }}>
      <SettingsGroup title="Accounts" description="Connected mailboxes shown in the sidebar.">
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {accounts.map((a) => (
            <div key={a.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '12px 0', borderBottom: '1px solid var(--navy-50)' }}>
              <span style={{ width: 32, height: 32, borderRadius: '50%', background: `var(--tag-${a.tag}-bg)`, color: `var(--tag-${a.tag}-fg)`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-body)', fontSize: 13, fontWeight: 700, flexShrink: 0 }}>{initials(a.label)}</span>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontFamily: 'var(--font-body)', fontSize: 14.5, fontWeight: 600, color: 'var(--text-primary)' }}>{a.label}</div>
                <div style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--text-tertiary)' }}>{a.email}</div>
              </div>
              <Button variant="ghost" size="sm">Remove</Button>
            </div>
          ))}
          <div style={{ paddingTop: 14 }}>
            <Button variant="secondary" size="sm">Add account</Button>
          </div>
        </div>
      </SettingsGroup>

      <SettingsGroup title="Notifications">
        <SettingRow title="Desktop notifications" description="Show a system notification for new mail while Hey Pigeon is open." control={<Switch checked={desktopNotif} onChange={(e) => setDesktopNotif(e.target.checked)}/>}/>
        <SettingRow title="Notification sound" description="Play a sound when new mail arrives." control={<Switch checked={notifSound} onChange={(e) => setNotifSound(e.target.checked)}/>}/>
        <SettingRow title="Preview content" description="What to show in a new mail notification." control={
          <Select value={notifPreview} onChange={(e) => setNotifPreview(e.target.value)} options={[
            { value: 'sender-subject', label: 'Sender & subject' },
            { value: 'sender-only', label: 'Sender only' },
            { value: 'none', label: 'Nothing' },
          ]}/>
        }/>
      </SettingsGroup>

      <SettingsGroup title="Appearance">
        <SettingRow title="Theme" description="Match your system, or set Hey Pigeon independently." control={
          <div style={{ display: 'flex', gap: 18 }}>
            {[['system', 'System'], ['light', 'Light'], ['dark', 'Dark']].map(([v, l]) => (
              <Radio key={v} name="theme" label={l} checked={theme === v} onChange={() => setTheme(v)}/>
            ))}
          </div>
        }/>
        <SettingRow title="List density" description="How much space each message row takes up." control={
          <Select value={density} onChange={(e) => setDensity(e.target.value)} options={[
            { value: 'comfortable', label: 'Comfortable' },
            { value: 'compact', label: 'Compact' },
          ]}/>
        }/>
      </SettingsGroup>

      <SettingsGroup title="Inbox" description="Control how messages are grouped and which actions appear on hover.">
        <SettingRow title="Pinned list" description="Group pinned messages at the top of your inbox, above the rest." control={<Switch checked={pinListEnabled} onChange={(e) => onPinListChange(e.target.checked)}/>}/>
        <SettingRow title="Hover actions" description="Drag up to 3 actions into the box to show them when you hover a message." control={null}/>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14, padding: '0 0 16px' }}>
          <div>
            <div style={{ fontFamily: 'var(--font-body)', fontSize: 12, color: 'var(--text-tertiary)', marginBottom: 6 }}>Selected (drag to reorder)</div>
            <div onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); reorderOrAdd(hoverActions.length); }}
              style={{ display: 'flex', gap: 8, minHeight: 40, alignItems: 'center', padding: 8, border: '1px dashed var(--border-default)', borderRadius: 'var(--radius-md)' }}>
              {hoverActions.map((k, i) => {
                const a = window.EMAIL_ACTIONS.find((x) => x.key === k);
                if (!a) return null;
                return (
                  <span key={k} draggable onDragStart={() => setDragKey(k)} onDragEnd={() => setDragKey(null)}
                    onDragOver={(e) => { e.preventDefault(); e.stopPropagation(); }} onDrop={(e) => { e.preventDefault(); e.stopPropagation(); reorderOrAdd(i); }}
                    style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '6px 6px 6px 12px', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-pill)', fontFamily: 'var(--font-body)', fontSize: 13, fontWeight: 600, color: 'var(--text-primary)', cursor: 'grab' }}>
                    {a.label}
                    <button onClick={() => onHoverActionsChange(hoverActions.filter((x) => x !== k))} style={{ border: 'none', background: 'none', cursor: 'pointer', color: 'var(--text-tertiary)', display: 'flex', padding: 4 }}>
                      <svg width="11" height="11" viewBox="0 0 24 24" fill="none"><path d="M6 6l12 12M18 6L6 18" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
                    </button>
                  </span>
                );
              })}
              {hoverActions.length === 0 && <span style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--text-tertiary)' }}>Drop actions here</span>}
            </div>
          </div>
          <div>
            <div style={{ fontFamily: 'var(--font-body)', fontSize: 12, color: 'var(--text-tertiary)', marginBottom: 6 }}>Available</div>
            <div onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); if (dragKey) onHoverActionsChange(hoverActions.filter((k) => k !== dragKey)); setDragKey(null); }}
              style={{ display: 'flex', gap: 8, flexWrap: 'wrap', minHeight: 34, padding: 8 }}>
              {window.EMAIL_ACTIONS.filter((a) => !hoverActions.includes(a.key)).map((a) => (
                <span key={a.key} draggable onDragStart={() => setDragKey(a.key)} onDragEnd={() => setDragKey(null)}
                  style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '6px 12px', background: 'var(--surface-card)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-pill)', fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--text-secondary)', cursor: 'grab' }}>
                  {a.label}
                </span>
              ))}
            </div>
          </div>
        </div>
      </SettingsGroup>

      <SettingsGroup title="Reading & replying">
        <SettingRow title="Include signature" description="Add your signature to new messages automatically." control={<Switch checked={signature === 'true'} onChange={(e) => setSignature(e.target.checked ? 'true' : 'false')}/>}/>
        {signature === 'true' && (
          <div style={{ padding: '0 0 16px' }}>
            <textarea value={signatureText} onChange={(e) => setSignatureText(e.target.value)} rows={4}
              style={{ width: '100%', boxSizing: 'border-box', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: 12, resize: 'vertical', fontFamily: 'var(--font-body)', fontSize: 13.5, color: 'var(--text-primary)', outline: 'none' }}/>
          </div>
        )}
        <SettingRow title="Send read receipts" description="Let senders know when you've opened their message." control={<Switch checked={readReceipts} onChange={(e) => setReadReceipts(e.target.checked)}/>}/>
        <SettingRow title="Swipe right on a message" description="Choose what a right swipe does in the inbox list." control={
          <Select value={swipeRight} onChange={(e) => setSwipeRight(e.target.value)} options={[
            { value: 'done', label: 'Mark done' },
            { value: 'delete', label: 'Delete' },
            { value: 'snooze', label: 'Snooze' },
          ]}/>
        }/>
        <SettingRow title="After archiving or deleting" description="Which message to open next." control={
          <Select value={autoAdvance} onChange={(e) => setAutoAdvance(e.target.value)} options={[
            { value: 'newer', label: 'Newer message' },
            { value: 'older', label: 'Older message' },
            { value: 'list', label: 'Back to list' },
          ]}/>
        }/>
      </SettingsGroup>

      <SettingsGroup title="Privacy">
        <SettingRow title="Block external images by default" description="Stop remote images from loading until you choose to show them, to limit sender tracking." control={<Switch checked={blockTracking} onChange={(e) => setBlockTracking(e.target.checked)}/>}/>
      </SettingsGroup>
    </div>
  );
}
window.Settings = Settings;
